import db from '../db.js';
import { studentsTable } from './schema.js';
const seed = async () => {
    await db.insert(studentsTable).values([
        { firstName: 'Amara', lastName: 'Osei', studentId: 'STU-100002', email: 'amara.osei@university.edu', phone: '555-304-2918', gender: 'Female', dob: '2002-07-22', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.A.', major: 'Psychology', program: 'Liberal Arts Program', admitTerm: 'Fall 2021' },
        { firstName: 'Liam', lastName: 'Nguyen', studentId: 'STU-100003', email: 'liam.nguyen@university.edu', phone: '555-412-5630', gender: 'Male', dob: '2000-11-05', level: 'Graduate', studentType: 'Full-Time', degree: 'M.S.', major: 'Data Science', program: 'Graduate STEM', admitTerm: 'Spring 2022' },
        { firstName: 'Sofia', lastName: 'Reyes', studentId: 'STU-100004', email: 'sofia.reyes@university.edu', phone: '555-518-7742', gender: 'Female', dob: '2001-01-30', level: 'Undergraduate', studentType: 'Part-Time', degree: 'B.B.A.', major: 'Business Admin', program: 'Business Program', admitTerm: 'Fall 2020' },
        { firstName: 'Marcus', lastName: 'Thompson', studentId: 'STU-100005', email: 'marcus.thompson@university.edu', phone: '555-623-8851', gender: 'Male', dob: '1999-09-18', level: 'Graduate', studentType: 'Full-Time', degree: 'M.B.A.', major: 'Business Leadership', program: 'MBA Program', admitTerm: 'Fall 2022' },
        { firstName: 'Yuki', lastName: 'Tanaka', studentId: 'STU-100006', email: 'yuki.tanaka@university.edu', phone: '555-731-9960', gender: 'Female', dob: '2003-04-11', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.S.', major: 'Biology', program: 'Pre-Med Program', admitTerm: 'Fall 2022' },
        { firstName: 'Elijah', lastName: 'Brooks', studentId: 'STU-100007', email: 'elijah.brooks@university.edu', phone: '555-840-1123', gender: 'Male', dob: '2001-06-27', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.S.', major: 'Mechanical Eng.', program: 'Engineering Program', admitTerm: 'Spring 2021' },
        { firstName: 'Fatima', lastName: 'Al-Hassan', studentId: 'STU-100008', email: 'fatima.alhassan@university.edu', phone: '555-947-2234', gender: 'Female', dob: '2000-12-03', level: 'Graduate', studentType: 'Part-Time', degree: 'M.A.', major: 'Education', program: 'Graduate Education', admitTerm: 'Fall 2021' },
        { firstName: 'Noah', lastName: 'Patel', studentId: 'STU-100009', email: 'noah.patel@university.edu', phone: '555-053-3345', gender: 'Male', dob: '2002-08-15', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.S.', major: 'Mathematics', program: 'STEM Program', admitTerm: 'Fall 2021' },
        { firstName: 'Isabelle', lastName: 'Moreau', studentId: 'STU-100010', email: 'isabelle.moreau@university.edu', phone: '555-162-4456', gender: 'Female', dob: '2001-05-09', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.A.', major: 'French Literature', program: 'Humanities Program', admitTerm: 'Fall 2020' },
        { firstName: 'Darius', lastName: 'Williams', studentId: 'STU-100011', email: 'darius.williams@university.edu', phone: '555-271-5567', gender: 'Male', dob: '1998-02-21', level: 'Graduate', studentType: 'Full-Time', degree: 'Ph.D.', major: 'Computer Science', program: 'Doctoral Program', admitTerm: 'Fall 2019' },
        { firstName: 'Chloe', lastName: 'Kim', studentId: 'STU-100012', email: 'chloe.kim@university.edu', phone: '555-380-6678', gender: 'Female', dob: '2002-10-17', level: 'Undergraduate', studentType: 'Part-Time', degree: 'B.F.A.', major: 'Graphic Design', program: 'Arts Program', admitTerm: 'Spring 2022' },
        { firstName: 'Andre', lastName: 'Santos', studentId: 'STU-100013', email: 'andre.santos@university.edu', phone: '555-489-7789', gender: 'Male', dob: '2001-07-04', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.S.', major: 'Civil Engineering', program: 'Engineering Program', admitTerm: 'Fall 2020' },
        { firstName: 'Priya', lastName: 'Sharma', studentId: 'STU-100014', email: 'priya.sharma@university.edu', phone: '555-597-8890', gender: 'Female', dob: '2000-03-28', level: 'Graduate', studentType: 'Full-Time', degree: 'M.S.', major: 'Biomedical Eng.', program: 'Graduate STEM', admitTerm: 'Spring 2023' },
        { firstName: 'Owen', lastName: 'Mitchell', studentId: 'STU-100015', email: 'owen.mitchell@university.edu', phone: '555-604-9901', gender: 'Male', dob: '2003-01-13', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.S.', major: 'Physics', program: 'STEM Program', admitTerm: 'Fall 2022' },
        { firstName: 'Aaliyah', lastName: 'Johnson', studentId: 'STU-100016', email: 'aaliyah.johnson@university.edu', phone: '555-713-0012', gender: 'Female', dob: '2002-06-06', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.A.', major: 'Sociology', program: 'Social Sciences', admitTerm: 'Fall 2021' },
        { firstName: 'Ethan', lastName: 'Clarke', studentId: 'STU-100017', email: 'ethan.clarke@university.edu', phone: '555-822-1123', gender: 'Male', dob: '1997-11-25', level: 'Graduate', studentType: 'Part-Time', degree: 'M.S.', major: 'Cybersecurity', program: 'Graduate STEM', admitTerm: 'Fall 2023' },
        { firstName: 'Maya', lastName: 'Robinson', studentId: 'STU-100018', email: 'maya.robinson@university.edu', phone: '555-931-2234', gender: 'Female', dob: '2001-09-19', level: 'Undergraduate', studentType: 'Full-Time', degree: 'B.S.', major: 'Nursing', program: 'Health Sciences', admitTerm: 'Fall 2020' },
        { firstName: 'Sebastian', lastName: 'Lopez', studentId: 'STU-100019', email: 'sebastian.lopez@university.edu', phone: '555-040-3345', gender: 'Male', dob: '2000-04-02', level: 'Undergraduate', studentType: 'Part-Time', degree: 'B.B.A.', major: 'Finance', program: 'Business Program', admitTerm: 'Spring 2021' },
        { firstName: 'Zoe', lastName: 'Anderson', studentId: 'STU-100020', email: 'zoe.anderson@university.edu', phone: '555-149-4456', gender: 'Non-binary', dob: '2002-12-31', level: 'Graduate', studentType: 'Full-Time', degree: 'M.A.', major: 'Political Science', program: 'Graduate Social Sci.', admitTerm: 'Fall 2023' },
    ]);
    console.log('Seeded 20 students.');
    process.exit(0);
};
seed();
//# sourceMappingURL=seed.js.map