name: Deploy nodejs-student-service

env:
  APP_NAME: "nodejs-student-service"
  APP_DIR: "/var/www/nodejs-student-service"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ─── JOB 1: Test ───────────────────────────────────────
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Build app
        run: npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          timeout: 60s
          script: |
            APP_DIR=/var/www/nodejs-student-service
            APP_NAME=nodejs-student-service

            # ── 1. Safety checks ──────────────────────────────────────
            if [ -z "$APP_DIR" ]; then
              echo "ERROR: APP_DIR is empty, aborting!"
              exit 1
            fi

            DEPTH=$(echo "$APP_DIR" | tr -cd '/' | wc -c)
            if [ "$DEPTH" -lt 3 ]; then
              echo "ERROR: APP_DIR '$APP_DIR' is too shallow, aborting!"
              exit 1
            fi

            BLOCKED="/ /var /var/www /home /etc /usr /bin /sbin"
            for BLOCKED_PATH in $BLOCKED; do
              if [ "$APP_DIR" = "$BLOCKED_PATH" ]; then
                echo "ERROR: APP_DIR '$APP_DIR' is a protected path, aborting!"
                exit 1
              fi
            done

            echo "✅ Safety checks passed for $APP_DIR"

            # ── 2. Safety checks ──────────────────────────────────────
            # Install Node.js 18
            sudo dnf install -y nodejs

            # Verify
            node -v && npm -v

            # ── 3. Safe remove ────────────────────────────────────────
            if [ -d "$APP_DIR" ]; then
              echo "Directory exists — removing safely..."
              sudo chown -R $USER:$USER "$APP_DIR"
              sudo rm -rf "$APP_DIR"
              echo "✅ Removed $APP_DIR"
              sudo mkdir -p "$APP_DIR"
              sudo chown -R $USER:$USER "$APP_DIR"
              echo "✅ Recreated $APP_DIR"
            else
              echo "Directory does not exist — creating..."
              sudo mkdir -p "$APP_DIR"
              sudo chown -R $USER:$USER "$APP_DIR"
              echo "✅ Created $APP_DIR"
            fi



            # ── 4. Git, Clone or pull latest code ──────────────────────────
            echo "Installing git..."
            sudo dnf install -y git
            echo "✅ Git installed"
            echo "Cloning repository..."
            sudo git clone https://${{ secrets.G_HUB_USERNAME }}:${{ secrets.G_HUB_TOKEN }}@github.com/${{ secrets.G_HUB_USERNAME }}/${{ secrets.G_HUB_REPOSITORY }}.git "$APP_DIR"
            echo "✅ Clone complete"

            # ── 4. Install dependencies ───────────────────────────────
            echo "Installing dependencies..."
            cd "$APP_DIR"
            npm ci --omit=dev
            echo "✅ Dependencies installed"

            # ── 6. Build on EC2 ───────────────────────────────────────
            echo "Building the application.."
            npm run build
            echo "✅ Build complete"

            # Migrate all new SQl schema changes - using drizzle-kit push
            echo "Migrating database schema changes..."
            npm run db:push
            sudo systemctl restart postgresql
            echo "✅ Database migration completed"

            # ── 4. Restart app with PM2 ───────────────────────────────
            pm2 start dist/index.js --name "$APP_NAME" -i max

            pm2 save

            echo "✅ Deployment successful!"
