name: Deploy nodejs-student-service

env:
  APP_NAME: "nodejs-student-service"
  APP_DIR: "/var/www/nodejs-student-service"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # ─── JOB 1: Test ───────────────────────────────────────
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Clear npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

      - name: Build app
        run: npm run build

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            APP_DIR="/var/www/nodejs-student-service"
            APP_NAME="nodejs-student-service"

            # ── 1. Remove any existing Node.js versions and Install new Nodejs ──────────────────────────
            echo "Removing and installing a new Node.js..."
            sudo dnf remove -y nodejs

            # Install Node.js 18
            sudo dnf install -y nodejs

            # Verify
            node -v && npm -v

            # ── 2. Cremove current app folder if existing ──────────────────────────
            echo "Removing old app directory..."
            if [ -d "$APP_DIR" ]; then
              sudo chown -R $USER:$USER $APP_DIR
              sudo rm -rf $APP_DIR
              echo "Removed $APP_DIR"
            else
              echo "Folder does not exist, skipping..."
            fi

            # ── 3. Create new app folder directory ──────────────────────────
            # Ensure the directory exists and is owned by your user
            echo "Ensure the directory exists and is owned by your user..."
            sudo mkdir -p $APP_DIR
            sudo chown -R $USER:$USER $APP_DIR
            sudo chown -R $USER:$USER $APP_DIR

            # ── 4. Clone or pull latest code ──────────────────────────
            if [ -d "$APP_DIR/.git" ]; then
              echo "Repo exists — pulling latest changes..."
              cd $APP_DIR
              git pull https://${{ secrets.G_HUB_USERNAME }}:${{ secrets.G_HUB_TOKEN }}@github.com/${{ secrets.G_HUB_USERNAME }}/${{ secrets.G_HUB_REPOSITORY }}.git main
            else
              echo "Fresh clone..."
              rm -rf $APP_DIR
              git clone https://${{ secrets.G_HUB_USERNAME }}:${{ secrets.G_HUB_TOKEN }}@github.com/${{ secrets.G_HUB_USERNAME }}/${{ secrets.G_HUB_REPOSITORY }}.git $APP_DIR
              cd $APP_DIR
            fi

            # ── 5. Clean install dependencies (production only) ───────────────────────────────────────
            echo "Clean installing all dependencies..."
            npm ci --omit=dev

            # ── 6. Build on EC2 ───────────────────────────────────────
            echo "Building the application.."
            npm run build

            # Migrate all new SQl schema changes - using drizzle-kit push
            echo "Migrating database schema changes..."
            npm run db:push
            sudo systemctl restart postgresql

            # ── 4. Restart app with PM2 ───────────────────────────────
            pm2 start dist/index.js --name "$APP_NAME" -i max

            pm2 save

            echo "✅ Deployment successful!"
